name: deploy-harry-potter-app

on:
  push:
    branches:
      - main
    paths:
      - "harry-potter-app/**"

defaults:
  run:
    working-directory: harry-potter-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run build

      - name: Deploy to S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/harry-potter-app/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID}} --path "/harry-potter-app/latest/remoteEntry.js"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID}}
          AWS_DEFAULT_REGION: "us-east-1"
